// The Rainbow Connection

object RainbowConnection {

  def main(args: Array[String]): Unit = {
    println("Why are there so many songs about rainbows?")
    println("And what's on the other side?")
    println("Rainbows are visions, they're only illusions")
    println("And rainbows have nothing to hide")
    println("So we've been told and some chose to believe it")
    println("But I know they're lying, wait and see")
    println("Some day we'll find it, the Rainbow Connection")
    println("The lovers, the dreamers, and me")
    println()
    println("Who said that every wish would be heard and answered")
    println("When wished on the morning star")
    println("Somebody thought of that and someone believed it")
    println("Look what it's done so far")
    println("What's so amazing that keeps us stargazing")
    println("And what do we think we might see?")
    println("Some day we'll find it, the Rainbow Connection")
    println("The lovers, the dreamers, and me")
    println()
    println("All of us under its spell, we know that it's probably magic")
    println("Have you been half asleep and have you heard voices?")
    println("I've heard them calling my name")
    println("Is this the sweet sound that called the young sailors")
    println("The voice might be one and the same")
    println("I've heard it too many times to ignore it")
    println("It's something that I'm supposed to be")
    println("Some day we'll find it, the Rainbow Connection")
    println("The lovers, the dreamers, and me")
    println()
    println("La la la la la")
    println("La la la la lee")
    println("La la la la la")
    println("La la la la lee")
    println()
    println("Have you been half asleep and have you heard voices?")
    println("I've heard them calling my name")
    println("Is this the sweet sound that called the young sailors")
    println("The voice might be one and the same")
    println("I've heard it too many times to ignore it")
    println("It's something that I'm supposed to be")
    println("Some day we'll find it, the Rainbow Connection")
    println("The lovers, the dreamers, and me")
  }
}